name: Sync to Hugging Face

on:
  push:
    branches: [main]
  # Allows manual triggering
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces Hub via Git
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote add hf https://vedika24:$HF_TOKEN@huggingface.co/spaces/vedika24/neuro-symbolic-compliance-api
          git push --force hf HEAD:main

